resources:
  - name: spring-boot-concourse
    type: git
    check_every: 10s
    source:
      uri: https://github.com/bmullan-pivotal/Concourse-Maven-Demo
      branch: master

jobs:
- name: build
  public: true
  plan:
  - get: spring-boot-concourse
    trigger: true
  - task: Build project
    file: concourse/tasks/build.yml
  - task: Deploy artifact
    file: concourse/tasks/deploy.yml
